### ISSUE TITLE
`conda mambabuild` does not respect passed channels

### ISSUE THREAD

**Issue by matthewwardrop** [mamba-org/boa#102]
Greetings all,

I love how much fast `mamba` is over `conda`, but am having a little trouble getting it to respect conda overrides during the build process. `conda mambabuild -c conda-forge <recipe>` does not cause mamba to look at the conda-forge channel (it just continues to look at the default channels of the host environment). Is that expected?

**Comment by wolfv** [comment]
I would be happy about a PR to parse more cmd line args and add them to the config.

**Comment by wolfv** [comment]
if you configure your condarc file it should work out of the box.

**Comment by wolfv** [comment]
I have a fix for this.

**Comment by matthewwardrop** [comment]
Hey... thanks Wolf! I had meant to get back to you about looking into this... But life!
