### ISSUE TITLE
KeyError with private channel packages

### ISSUE THREAD

**Issue by wenjuno** [mamba-org/boa#118]
This is basically the same problem as https://github.com/mamba-org/mamba/issues/655. Can we apply the same patch as https://github.com/mamba-org/mamba/pull/669 or are you thinking about a better solution (based on https://github.com/mamba-org/mamba/issues/684)? Thanks.

`lookup_dict` in `to_action` function:
https://github.com/mamba-org/boa/blob/3da08ce12802cf28d6338523b1daa1261b061b76/boa/core/solver.py#L46-L62

**Comment by wolfv** [comment]
I've used hte same code here now. I am releasing 0.4.0 right now, let me know if that works for you.
