### ISSUE TITLE
custom pkgs_dirs ignored by MambaSolver

### ISSUE THREAD

**Issue by tl-hbk** [mamba-org/boa#124]
According to the [conda docs](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-package-directories-pkgs-dirs) you can set `pkgs_dirs` in `.condarc` or set the environment variable `CONDA_PKGS_DIRS` to specify a different directory than the default for packages.  

When using `conda mambabuild ...` it seems that when `mamba_get_install_actions` is creating a `MambaSolver` it ignores the specified `pkgs_dirs` when loading channels

https://github.com/mamba-org/boa/blob/8cec2f0e374361fe6b6a83fde52b51d05e5f926a/boa/cli/mambabuild.py#L38-L55

https://github.com/mamba-org/boa/blob/8cec2f0e374361fe6b6a83fde52b51d05e5f926a/boa/core/solver.py#L108-L118

This can be observed through the following script
```
#!/usr/bin/env bash
source ~/anaconda3/etc/profile.d/conda.sh
conda create -q -y -p /tmp/pkgs_bug -c conda-forge python=3.7 mamba=0.7.14 boa=0.3.5
conda activate /tmp/pkgs_bug
export CONDA_PKGS_DIRS=/tmp/pkgs
conda mambabuild <some test package>
```

While during the actual solving it does use the correct location because it uses `conda_build.conda_interface.pkgs_dirs` instead of relying on the overwritten `api_ctx.pkgs_dirs`, during the initial `load_channels` in the `MambaSolver` constructor it attempts to create the package cache in  `$conda_prefix/pkgs`

https://github.com/mamba-org/boa/blob/8cec2f0e374361fe6b6a83fde52b51d05e5f926a/boa/core/solver.py#L154-L156

**Comment by tl-hbk** [comment]
The fix for this doesn't seem too major although I'd like insight on if there's a reason the values set in this pull request are preferred over the values set in `mamba.utils.init_api_context`

https://github.com/mamba-org/boa/pull/67/commits/bb3dbfa447cca580fbcfc7b766fa92d18afbfe3b

https://github.com/mamba-org/mamba/blob/a6fc0d6a4ee2d10cee0b86065d77b7deb58e8ff2/mamba/utils.py#L165-L168

**Comment by wolfv** [comment]
yes, it's possible that this code can be changed now. I'd be happy about a PR!

**Comment by wolfv** [comment]
Thanks for the fix @tl-hbk
