### ISSUE TITLE
mambabuild: virtual packages in test env

### ISSUE THREAD

**Issue by wolfv** [mamba-org/boa#131]
It seems that virtual packages are missing in the test environment.

**Comment by wolfv** [comment]
I've been running some tests and it looks like they are properly added, as expected. Still unsure what's going wrong in the above scenario (conda info shows that glibc virtual package has version 2.17 so it should be fine).

**Comment by s22chan** [comment]
this is affecting more builds now since many conda-forge feedstocks now add `__osx` restrictions on the MacOS targets

**Comment by wolfv** [comment]
This is actually a conda build problem...

**Comment by s22chan** [comment]
You can probably close this issue, it's working fine for me (at least for `__osx`) after I updated mamba, boa, and conda-build:

```
  boa                                   0.8.0  pyha770c72_0        conda-forge/noarch      48 KB
  conda                                4.11.0  py310h2ec42d9_0     conda-forge/osx-64      17 MB
  conda-build                          3.21.6  py310h2ec42d9_3     conda-forge/osx-64     572 KB
  mamba                                0.18.2  py310h795411f_0     conda-forge/osx-64      41 KB
```
