### ISSUE TITLE
conda mambabuild --notest broken in 0.4.1

### ISSUE THREAD

**Issue by mparry** [mamba-org/boa#133]
#128 seems to have broken this for `conda mambabuild` (can't comment on `boa`).

With boa 0.4.1 (and mamba 0.7.14) I now see this:

```
> conda mambabuild --no-copy-test-source-files --no-build-id --dirty --no-test some_package

Updating build index: ...
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 144, in main
    call_conda_build(action, config, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 125, in call_conda_build
    **kwargs,
TypeError: build() got multiple values for keyword argument 'notest'
```

I'm a bit confused as to why any change was necessary at all, because it works just fine in 0.4.0 AFAICT. (Though I'm then equally confused about #117, unless that perhaps is talking about an earlier version again.)

**Comment by wolfv** [comment]
ping @mariusvniekerk

**Comment by wolfv** [comment]
Thanks for the bug report, this should be fixed in master now. I am going to make a release today.
