### ISSUE TITLE
libsolv segfault when building with boa

### ISSUE THREAD

**Issue by tl-hbk** [mamba-org/boa#146]
There's a particular scenario when I use `boa` to try to build a package with only 2 build requirements where libsolv segfaults at the following section

https://github.com/openSUSE/libsolv/blob/35e172e9fb99594b49c630cb188dab9d2b2c4dc7/src/solver.c#L1583-L1589

when it tries to do `r->d`.

Unfortunately I do not have an easy way to reproduce this as it only occurs when an internally hosted channel is added to the `.condarc`.  When removed from the `.condarc` I'm no longer able to reproduce the segfault.  What I noticed though is that even if that channel is not actually used during the build it causes the segfault.  For example the `.condarc` would have 

```
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
  - internal_channel
```

but the command would be

```
conda mambabuild C:\path\to\recipe --python 3.4 -c https://repo.anaconda.com/pkgs/main -c https://repo.anaconda.com/pkgs/free
```

the segfault would still occur.  I tried adding logging to the solve memory allocation functions but didn't notice the segfaulting address being within any of the blocks of freed/reallocated memory.  The following is the last iteration of the loop in linked above before it segfaults

```
i: 87404, r: 0000021A33960260
p, d, w1, w2, n1, n2 = (30289, 40562, 30289, 30290, 0, 0)
solv_realloc: 0000021A31218300, end: 0000021A31218334, len: 52
dq->count: 13
solv_realloc: 0000021A313212B0, end: 0000021A313219F8, len: 1864
solv_realloc: 0000021A31320010, end: 0000021A31320758, len: 1864
solv_realloc: 0000021A313212B0, end: 0000021A31321AF8, len: 2120
solv_realloc: 0000021A31320010, end: 0000021A31320858, len: 2120
solv_realloc: 0000021A313212B0, end: 0000021A31321BF8, len: 2376
solv_realloc: 0000021A31320010, end: 0000021A31320958, len: 2376
calloc: 0000021A312E2FD0, num: 4676, len: 1
solv_realloc: 0000021A32767D10, end: 0000021A327B2710, len: 305664
free: 0000021A312E2FD0
solv_realloc: 0000021A331AD040, end: 0000021A333D5040, len: 2260992
olevel: 2, level: 2
i: 87404, r: 0000021A33960260
```

**Comment by tl-hbk** [comment]
Did narrow it down to it happening somewhere in `selectandinstall`.  Attempting to dereference `r` before the call to `selectandinstall` works but not after on the iteration where the segfault occurs

**Comment by wolfv** [comment]
Hi @tl-hbk indeed, hard for me to help accurately without being able to reproduce this. I haven't seen that before.

Two ideas:

- try with an older libsolv? Last releases didn't change much, but who knows.
- check that the repodata that is in your custom channel has all the fields that one would expect from e.g. conda-forge. I have seen cases where the repodata of non-CDN (everything except conda-forge/bioconda/main) channels didn't have the SHA256 sum and similar

But maybe this problem is somewhere else entirely ...

**Comment by tl-hbk** [comment]
I tried the 0.7.17 build before the regex fix and that didn't change anything.  Managed to track it down to here
https://github.com/openSUSE/libsolv/blob/35e172e9fb99594b49c630cb188dab9d2b2c4dc7/src/solver.c#L773-L784
https://github.com/openSUSE/libsolv/blob/35e172e9fb99594b49c630cb188dab9d2b2c4dc7/src/rules.c#L318-L320

Seems like when it tries to add a rule, if it runs out of memory it'll extend the memory allocated for rules.  
In my situation it couldn't just extend the current block of memory so it allocated a new memory block but 
https://github.com/openSUSE/libsolv/blob/35e172e9fb99594b49c630cb188dab9d2b2c4dc7/src/solver.c#L1634-L1639
just decrements the old pointer still pointing at the old location

**Comment by tl-hbk** [comment]
Have a fix I'll create PR in libsolv

**Comment by wolfv** [comment]
hey, thanks for digging so deep into libsolv (again!). I have never come across this before!

**Comment by wolfv** [comment]
PS: feel free to let me know when you have a patch / send the patch to https://github.com/conda-forge/libsolv-feedstock and we can release a patched version.

**Comment by tl-hbk** [comment]
@wolfv here's the PR for libsolv https://github.com/openSUSE/libsolv/pull/443 I don't know how to create a `.patch` file for the conda recipe though
