### ISSUE TITLE
`conda mambabuild conda.recipe --output` does not show the path and actually build the package

### ISSUE THREAD

**Issue by bloussou** [mamba-org/boa#157]
Hello,
The `--output` option should do the following : **Output the conda package filename which would have been created** but it does not when running `conda mambabuild conda.recipe --output`. It is building the package and not taking care of the `output` option.
Thanks for your work on mamba and boa it's very fast and nice !

**Comment by bloussou** [comment]
I have find a workaround setting the output directory using `--output-dir` and finding the package the the `noarch` folder.

**Comment by marscher** [comment]
It'd be great, if this interface would function as expected.

@bloussou Could you point me towards your work around?

**Comment by wolfv** [comment]
I don't really know the `--output` function, actually. Does it perform a render, and then outputs only the final file name (s)?

Would greatly appreciate contributions!

**Comment by marscher** [comment]
I guess that is exactly the procedure. https://github.com/conda/conda-build/blob/3b99b2222a067e113a2282926871cd1e5406ee2b/conda_build/api.py#L87

**Comment by wolfv** [comment]
there is a PR implementing this feature now. Could one of you test it?

What's the expected output format for you?

something like `["/path/to/myfile.tar.bz2", ...]`?

**Comment by marscher** [comment]
wow that was fast :+1:
