### ISSUE TITLE
boa build for noarch: python package

### ISSUE THREAD

**Issue by mariusvniekerk** [mamba-org/boa#159]
As shown in this example repo https://github.com/mariusvniekerk/boanoarch

boa build in this case produces an artifact that has incorrect contraints for python_abi.  It seems to be inheriting the python_abi constraints from the build/host env rather than ignoring them completely as conda-build does.

**Comment by wolfv** [comment]
Here is a similar issue on conda-build: https://github.com/conda/conda-build/issues/3956

And here is the PR that introduced an additional "noarch"-runexports type: https://github.com/conda/conda-build/pull/3868/files#diff-c54c378feea1d475af4a7c30e9be71e40de70f98c5e804e50e8c676569496f8a

We need to handle the noarch runexports to not add the python_abi package to the noarch run-dependencies.
