### ISSUE TITLE
Support variant files in mambabuild

### ISSUE THREAD

**Issue by xhochy** [mamba-org/boa#17]
One of the useful features of `mamba` is that its resolver errors are much more readable. In conda-forge PRs, we often run into problems where a resolution due to the constraints given by the global pinnings file cannot be resolved. Here it would be useful to take `conda mambabuild` to get a different error using `conda mambabuild -m .ci_support/osx_r_base3.6target_platformosx-64.yaml recipe`.

**Comment by wolfv** [comment]
yeah that makes sense! We should copy over the argument parsing from conda build.

**Comment by wolfv** [comment]
@beckermr was also looking at this and mentioned that we might be able to re-use conda-build's command line interface. I also think that's possible -- we just need to figure out how to call it here:

https://github.com/TheSnakePit/boa/blob/b38490674f43f53467239136789d3252ac57d987/boa/cli/mambabuild.py#L267-L281

@beckermr did you find the time to look into this?

**Comment by beckermr** [comment]
No sorry! The cos7 stuff needed more work. Maybe in the coming week but it seems unlikely right now.

**Comment by wolfv** [comment]
No worries. I can have a look as well.
