### ISSUE TITLE
broken mambabuild with extra .*

### ISSUE THREAD

**Issue by beckermr** [mamba-org/boa#196]
See this build: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=395617&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642

cc @wolfv

**Comment by wolfv** [comment]
fixed in #204

**Comment by wolfv** [comment]
and released as 0.7.1
