### ISSUE TITLE
Mambabuild failing during packaging on Windows

### ISSUE THREAD

**Issue by WardBrian** [mamba-org/boa#197]
This issue was noticed during an update to a conda-forge feedstock here: https://github.com/conda-forge/cmdstan-feedstock/pull/10

Here is a log with their mambabuild support enabled:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/395697/logs/21

and one which worked before it was enabled:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/387623/logs/30

**Comment by wolfv** [comment]
It appears that the issue with cmdstan has "resolved itself" - possibly it was related to LIEF after all.

**Comment by markotoplak** [comment]
Thanks! I'll test on our repo and report back.

**Comment by WardBrian** [comment]
I guess this really did resolve itself then
