### ISSUE TITLE
New release to support mamba >=0.18

### ISSUE THREAD

**Issue by duncanmmacleod** [mamba-org/boa#220]
`boa` is great, `mamba` is great, thanks for both!

It would be even greater to have a new release of `boa` that is compatible with `mamba >=0.18`, is there a chance of getting that soon?

**Comment by traversaro** [comment]
I guess this was fixed by https://github.com/mamba-org/boa/pull/221 and https://github.com/conda-forge/boa-feedstock/pull/35 .

**Comment by wolfv** [comment]
yep! :)
