### ISSUE TITLE
Exceptions appear to be truncated?

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/boa#242]
I'm getting an error with `boa build`:

![image](https://user-images.githubusercontent.com/881019/154277052-43ad20ed-af2e-45af-bdac-c8f7ecda40b9.png)

----

![image](https://user-images.githubusercontent.com/881019/154276695-abcb5c06-2093-45c7-9b84-dba8890874fe.png)

Unfortunately, it seems to be truncated and missing the *actual* error which occurred?

**Comment by dhirschfeld** [comment]
```
❯ mamba list boa
# packages in environment at /opt/mambaforge/envs/bld:
#
# Name                    Version                   Build  Channel
boa                       0.9.0              pyha770c72_0    conda-forge
```
***xref:*** #243

**Comment by dhirschfeld** [comment]
ok, that was some sort of heisenbug - I moved my terminal to a new screen and tried again and the traceback now renders correctly

**Comment by wolfv** [comment]
Hmm, maybe it had somethign to do with the progress bar not having finished rendering? Hard to tell, will keep an eye out for bugs like this :)

**Comment by dhirschfeld** [comment]
Some sort of terminal rendering bug. An interesting data point in case it crops up in future but nothing which needs following up now I think.
