### ISSUE TITLE
`boa` CLI should have a `--version` method

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/boa#243]

**Comment by wolfv** [comment]
Yes, I did actually notice this today as well!

**Comment by dhirschfeld** [comment]
Since you're printing the banner you could perhaps add a byline with the version similar to mamba?

But a --version method would be good too.

**Comment by dhirschfeld** [comment]
Probably something I could put in a PR for myself! 😅 

![image](https://user-images.githubusercontent.com/881019/154371406-c99d0118-734a-4fec-8d99-9240f882bf4a.png)
