### ISSUE TITLE
Is the binary_relocation flag supported?

### ISSUE THREAD

**Issue by frmdstryr** [mamba-org/boa#254]
packages built with boa seem to override the rpath set (or removed) by the build script. 

```
 readelf --dynamic android-libuuid-1.0.3-h4616a5c_1/android/x86/lib/libuuid.so | grep RPATH
 0x0000000f (RPATH)                      Library rpath: [$ORIGIN/../../../lib]
```

It looks like the `binary_relocation` flag is being ignored?

**Comment by wolfv** [comment]
Does this also fix your other issue re. noarch packages?
