### ISSUE TITLE
build process step

### ISSUE THREAD

**Issue by magic0121** [mamba-org/boa#282]
Hi

I have the following code structure

>abc
>>packing
>>>files
>>>>recipe.yaml
>>>>meta.yaml

>>>pip
>>>>pyproject.toml
>>>>setup.cfg
>>>>MANIFEST.in

>src
 >>raw python packages

>tests
 >>test packages

so, from dir abc, I'm trying to run

boa build packing/files/

However I'm getting the error

ATTENTION: No files added in target abc

in my recipe.yaml, I have the lines

sources:
  path: ../../.

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed ./packing/pip/
  noarch: python

and in setup.cfg, I have

[options]
packages = find:
python_requires  =  >=3.7
include_package_data = True

[options.packages.find]
where = ../../src

The boa build does produce a tar ball but strangely, it contains the tests code but not the src code.  I feel that the issue is around [options.package.find] however I couldn't get it to work after modifying it. This all works with 

conda build packing/files/meta.yaml

so how can we fix this the boa build?

Kind Regards

**Comment by wolfv** [comment]
Hi @magic0121 

From what I can see, your code looks fine. If you can share the rest of your recipe, I could take a closer look.

**Comment by magic0121** [comment]
Thanks wolfv, sorry for the delay. I just updated the desc, let me know if you need more info. 

Kind Regards

**Comment by magic0121** [comment]
Hi @wolfv 

Any thoughts on the updated comments at all? Keen to solve this, many thanks for your help here.

**Comment by magic0121** [comment]
Resolved. In recipe.yaml requirements section, you need to make use you use 'host' python rather than 'build' python
