### ISSUE TITLE
Source: section with git_url fails json schema validation when folder option is used

### ISSUE THREAD

**Issue by alexshagiev** [mamba-org/boa#309]
when folder option is removed validation passes successfully 

![033AC26B-FC58-4D43-996E-F5ED3847566A](https://user-images.githubusercontent.com/24636886/203151100-0526d7a8-ce3a-44f8-8a5d-60bb9a611b2c.jpeg)

**Comment by alexshagiev** [comment]
Looking up the schema and it seems to want me to use destination instead of folder tag, perhaps it is just read me.md update 

https://boa-build.readthedocs.io/en/latest/recipe_spec.html

**Comment by pelumi1163** [comment]
@alexshagiev 
Seems like this issue here https://github.com/mamba-org/boa/issues/313 could be the cause of what you are experiencing

**Comment by alexshagiev** [comment]
@pelumi1163  - i don't think so because i am using full path git & svn url and not relative path. However, since you pointed this out i see [this line](https://github.com/mamba-org/boa/blob/d439f21499d784ad471a7158f6f7d066afced1b1/boa/core/environ.py#L30) is expecting tag name to be `folder` instead `destination`. The issue i think is that at some point the [json yaml validation schema](https://github.com/mamba-org/boa/blob/d439f21499d784ad471a7158f6f7d066afced1b1/boa/schemas/recipe.v1.json#L147) was changed to use destination for svn , git, etc but the code still expects `folder`

**Comment by alexshagiev** [comment]
duplicate of #311 and should be resolved by #316
