### ISSUE TITLE
mambabuild: support for anaconda tokens

### ISSUE THREAD

**Issue by s22chan** [mamba-org/boa#31]
Similar to https://github.com/mamba-org/mamba/pull/370

Seems like a simple change to port, but I'm not sure about token leaks elsewhere in the code.

**Comment by wolfv** [comment]
I think that would be fine, yes! If you want to open a PR that would be great!

**Comment by s22chan** [comment]
I tried using the `get_index` from `mamba.utils` but it seems like the solver still can't find the packages. The solver cache does seem to have the packages there, so it looks like this change is a little bit harder than I initially thought.
