### ISSUE TITLE
[ feature request ] a conda-build --test like functionality in boa

### ISSUE THREAD

**Issue by harelwa** [mamba-org/boa#326]
Hi,

`conda-build` has a `--test` option used to run tests-only on a prebuilt package:

```bash
(base) > $ conda-build --help | grep "\--test"
  -t, --test            Test package (assumes package is already built).
```

the use case in my case is when building  a `noarch: python` package *once* and testing it on multiple python versions. for example for `python=3.10` i would run -- 

```bash
conad-build --tests path/to/tar.bz2 --extra-deps python=3.10
```

many thanks,

harel

**Comment by bollwyvl** [comment]
Adding to this, and a `--no-test`, as a prelude to _getting_ those pre-built packages: it would be useful to be able to confidently build a bunch of packages with complex `run`/`test` dependencies (but no `build` or `host` dependencies). This is prevented by [this discovery of `run`](https://github.com/mamba-org/boa/blob/main/boa/core/recipe_output.py#L596) deps. This is especially handy in CI.

**Comment by moqmar** [comment]
> [Building packages with unsolvable runtime dependencies] is prevented by [this discovery of run](https://github.com/mamba-org/boa/blob/main/boa/core/recipe_output.py#L596) deps.

This seems like a separate issue to me where run deps are installed even though they're not needed. Just removing that line would mean that it's possible to build non-installable packages, so I think this definitely needs to be a flag.
